project_id = "hqtrbbbrizislylzkhat"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-ad-strategy]
verify_jwt = false

[functions.generate-landing-page]
verify_jwt = false